--- LEFT JOIN - INNER JOIN - RIGHT JOIN --- --- Genelde LEFT JOIN çok kullanýlýr ---

--- Sadece iþleþen veriler gelir INNER JOIN , JOIN ---
SELECT U.USERNAME_, A.CITY FROM USERS U
JOIN ADRESS A ON A.USERID = U.ID

--- SOL TARAFTAKÝ BÜTÜN VERÝLER VE SAÐ TARAFTAKÝ SADECE EÞLEÞEN VERÝLER GELÝR - LEFT JOIN , LEFT OUTER JOIN ---,
SELECT U.USERNAME_, A.CITY FROM USERS U
LEFT JOIN ADRESS A ON A.USERID = U.ID

--- SAÐ TARAFTAKÝ BÜTÜN VERÝLER VE SOL TARAFTAKÝ SADECE EÞLEÞEN VERÝLER GELÝR - RIGHT JOIN , RIGHT OUTER JOIN ---,
SELECT U.USERNAME_, A.CITY FROM USERS U
RIGHT JOIN ADRESS A ON A.USERID = U.ID

--- NE VAR NE YOK HER ÞEYÝ GETÝRÝR FULL JOIN ---
SELECT U.USERNAME_, A.CITY FROM USERS U
FULL JOIN ADRESS A ON A.USERID = U.ID