---- ÝLÝÞKÝSEL VERÝTABANI ----

SELECT * FROM USERS
WHERE ID=1

SELECT * FROM ADDRESS
WHERE USERID=1

--- JOIN KULLANMADAN ÝLÝÞKÝSEL VERÝTABANI KULLANIMI (DAHA ZOR) ---

SELECT U.USERNAME_, U.NAMESURNAME,A.POSTALCODE, A.ADDRESSTEXT,
C.COUNTRY, A.CITYID, CT.CITY, T.TOWN, D.DISTRICT
FROM USERS U, ADDRESS A, COUNTRIES C,
CITIES CT, TOWNS T, DISTRICTS D

WHERE U.ID = A.USERID
AND A.COUNTRYID=C.ID
AND CT.ID = A.CITYID
AND T.ID = A.TOWNID
AND D.ID = A.DISTRICTID
 
AND U.ID=1


--- JOIN KULLANIMI ---

SELECT U.USERNAME_,U.NAMESURNAME,A.POSTALCODE,A.ADDRESSTEXT,
C.COUNTRY,CT.CITY, T.TOWN, D.DISTRICT
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
ORDER BY U.USERNAME_


--- ORDER, ORDER DETAÝLS, ITEMS TABLOLARI ÝLE JOIN KULLANIMI ---
SELECT O.ID, O.DATE_, O.TOTALPRICE,
U.USERNAME_, U.NAMESURNAME,
A.ADDRESSTEXT, A.POSTALCODE,
I.ITEMCODE, I.ITEMNAME, I.BRAND,I.CATEGORY1,
OD.AMOUNT, OD.UNITPRICE,OD.LINETOTAL
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE O.ID=1