SELECT 
CITY, DISTRICT,
COUNT(*) SATIRSAYISI, SUM(TOTALPRICE) TOPLAMSATIS ,AVG(TOTALPRICE) ORTSATIS ,MAX(TOTALPRICE) MAKSSATIS ,MIN(TOTALPRICE) MINSATIS
FROM SALES
WHERE CITY IN ('ANTALYA','ÝSTANBUL')
GROUP BY CITY, DISTRICT
ORDER BY CITY, DISTRICT